import type { Metadata } from "next";
import I18nProvider from "./I18nProvider";
import "./globals.css";
import WhIcon from "@/components/WhIcon";
import Nav from "@/components/Nav"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body>
        <I18nProvider>
          <Nav />
          {children}
          <WhIcon />
        </I18nProvider>
      </body>
    </html>
  );
}
